export const nationalityMap: { [key: string]: string } = {
  'British': 'gb',
  'Dutch': 'nl',
  'Mexican': 'mx',
  'Spanish': 'es',
  'German': 'de',
  'French': 'fr',
  'Italian': 'it',
  'Brazilian': 'br',
  'Monegasque': 'mc',
  'Finnish': 'fi',
  'Australian': 'au',
  'Canadian': 'ca',
  'Japanese': 'jp',
  'Thai': 'th',
  'Danish': 'dk',
  'American': 'us',
  'Argentine': 'ar',
  'Belgian': 'be',
  'Swiss': 'ch',
  'Irish': 'ie',
  'Polish': 'pl',
  'Swedish': 'se',
  'Russian': 'ru',
  'Venezuelan': 've',
  'Colombian': 'co',
  'Portuguese': 'pt',
  'Czech': 'cz',
  'Austrian': 'at',
  'Hungarian': 'hu',
  'Indonesian': 'id',
  'Malaysian': 'my',
  'Indian': 'in',
  'South African': 'za',
  'New Zealander': 'nz',
  'Chinese': 'cn',
  'Korean': 'kr',
  'Turkish': 'tr',
  'Greek': 'gr'
};